// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simple_Blazor_Todo.Server.Repositories;

namespace Simple_Blazor_Todo.Server.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Simple_Blazor_Todo.Shared.TodoItem", b =>
                {
                    b.Property<int>("TodoItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Titel")
                        .HasColumnType("text");

                    b.Property<int?>("TodoItemID1")
                        .HasColumnType("integer");

                    b.HasKey("TodoItemID");

                    b.HasIndex("TodoItemID1");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("Simple_Blazor_Todo.Shared.TodoItem", b =>
                {
                    b.HasOne("Simple_Blazor_Todo.Shared.TodoItem", null)
                        .WithMany("ChildItems")
                        .HasForeignKey("TodoItemID1");
                });
#pragma warning restore 612, 618
        }
    }
}
